compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
    styled-components@*:
        dependencies:
            react-is: '*'

yarnPath: .yarn/releases/yarn-4.3.1.cjs
